name: Compile with other repo dependency
on:
  push:
    branches:
      - main
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2          
        
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
            
        - name: Get branch name
          id: branch-name
          uses: tj-actions/branch-names@v5.1
          
        - name: Running on the default branch.
          if: steps.branch-name.outputs.is_default == 'true'
          run: |
            echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
          # Outputs: "Running on default: main".

        - name: Running on a pull request branch.
          if: steps.branch-name.outputs.is_default == 'false'
          run: |
            echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
          # Outputs: "Running on pr: feature/test".
