name: On create branch - Rename version pom.xml
on:
  create:
    branches:
      - main
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2          
        
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
            
        - name: Get branch name
          id: branch-name
          uses: tj-actions/branch-names@v5.1
          
        - name: Running on the default branch.
          if: steps.branch-name.outputs.is_default == 'true'
          run: |
            echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"

        - id: get-id
          run: |
            id=$(echo ${{ steps.branch-name.outputs.current_branch }} | cut -d] -f1 | cut -d[ -f2)
            echo "::set-output name=id::$id"
        - run: echo "${{steps.get-id.outputs.id}}"
        
        
        #Tarea extrae a la variable version, la version existente en el pom.xml
        - name: Extract Maven project version
          working-directory: ./example3-gitactions
          run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          #identificador asignado a la tarea
          id: project_version
          #Tarea que hace un echo de la variable creada en la tarea anterior
        - run: echo "Maven project version is ${{ steps.project_version.outputs.version }}"

        - id: get-id-version
          run: |
            id=$(echo ${{ steps.project_version.outputs.version }} | cut -d- -f1)
            echo "::set-output name=id::$id"
        - run: echo "${{steps.get-id-version.outputs.id}}"              
              
        - name: set version pom
          working-directory: ./example3-gitactions
          run: mvn -B versions:set -DnewVersion=${{ steps.get-id-version.outputs.id }}_${{ steps.get-id.outputs.id }}-SNAPSHOT -DgenerateBackupPoms=false
          
        - name: mvn package
          run: mvn -B package --file example3-gitactions/pom.xml
          
        - name: Commit new version
          run: |
            git config --global user.name 'Roberto'
            git config --global user.email 'roberto-pf@github.com'
            git add .
            git commit -am "Automated report"
            git push
